# Node.js with Angular
# Build a Node.js project that uses Angular.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- master

pool:
  vmImage: 'Ubuntu-16.04'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '11.x'
  displayName: 'Install Node.js'

- script: |
    cd ./Moonback
    npm install -g @angular/cli
    npm install
    ng build
  displayName: 'npm install and build'

- script: 
    cd ./Moonback  
    npm test
  displayName: 'npm front-end test'
  
- script: 
    cd ./Moonback  
    npm run lint
  displayName: 'npm pylint test'

- script: 
    cd ./server  
    npm test
  displayName: 'npm back-end test'

