# base image
FROM node:10.15.3-alpine

# set working directory
RUN mkdir -p /usr/src/moonback-back
WORKDIR /usr/src/moonback-back

# install and cache app dependencies
COPY package*.json ./
#https://github.com/kelektiv/node.bcrypt.js/wiki/Installation-Instructions#docker
RUN apk --no-cache add --virtual builds-deps build-base python
RUN npm install 

# add app
COPY . .
CMD node server